site_name: Manual Web14
site_url: https://web14.eu/docs
plugins:
  - search
  - print-site
theme:
  name: material
  language: es
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Inicio: 'index.md'
  - Servicios:
    - "Inicio de sesión": 'login.md'
  - Tutoriales:
    - Tailscale:
      - Adblock: 'vpn-adblock-tailscale.md'
  - Andromeda (Servidor):
    - Añadir nodo: 'andromeda/add-node.md'
